version: "3.8"

services:
  backend:
    build: .
    ports:
      - 8002:8002
    env_file:
      - .env
      
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myuser
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongodb_data:/data/db
  
volumes:
  mongodb_data: