### Create User
POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "name": "Putra",
    "email": "putrajaya@gmail.com",
    "password" : "putrajaya1234"
}

### Get All Users
GET http://localhost:3001/users-services/

### Get API
GET http://16.78.80.212:3001/

### Get User by ID
GET http://localhost:3001/users-services/66c5435841baf50cdaa368f5

### Login User
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "asepjaya@gmail.com",
    "password" : "asepjaya1234"
}

### Logout User
POST http://localhost:3001/auth/logout

### Delete User
DELETE http://localhost:3001/forumapp/api/v1/users-services/delete/66c5435841baf50cdaa368f5

### Update User
PATCH http://localhost:3001/users-services/update/66cc246cf49e2b8d810ac5ae
Content-Type: application/json

{
    "name": "Asep Munandar",
    "email": "asepjaya@gmail.com",
    "password" : "Asepjaya1234!"
}

