### Create User
POST http://localhost:8000/users-services
Content-Type: application/json

{
    "name": "Albert",
    "email": "iosefalbert@gmail.com",
    "password" : "albert1234"
}

### Get All Users
GET http://localhost:8000/users-services

### Get User by ID
GET http://localhost:8000/users-services/66c5435841baf50cdaa368f5

### Login User
POST http://localhost:8000/users-services/login
Content-Type: application/json

{
    "email": "iosefalbert@gmail.com",
    "password" : "albert1234"
}